import type { Node } from "@xyflow/react";

// A procedural-only platformer template — no Tiled / spritesheet assets yet,
// so it runs without any extra files. Player has gravity + jump + camera
// follow; the floor and platforms are graphicGroups with physicsType="fixed"
// so the Active player physically rests on them.
// Positions follow sidebar.tsx's `cleanupLayout` column order:
// col 0 (x=40) actor • col 2 (x=320) scene-1 entities • col 3 (x=600) scene-2
// entities • col 4 (x=880/1160) scenes • col 5 (x=1480) game.

export const platformerNodes: Node[] = [
  {
    id: "game-1",
    type: "game",
    position: { x: 1480, y: 40 },
    data: {
      label: "Game",
      width: 640,
      height: 360,
    },
  },
  {
    id: "scene-1",
    type: "scene",
    position: { x: 1160, y: 40 },
    data: {
      label: "Scene 1",
      width: 1600,
      height: 600,
      cellSize: 32,
      showGrid: false,
      backgroundColor: "blue",
      cameraX: 320,
      cameraY: 240,
      cameraZoom: 1,
    },
  },
  {
    id: "actor-1",
    type: "actor",
    position: { x: 40, y: 40 },
    style: { width: 240 },
    data: {
      label: "player",
      pos: { x: 120, y: 320 },
      color: "red",
      collision: true,
      tags: ["player"],
    },
  },
  {
    id: "inputModifier-platformer",
    type: "inputModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: { controls: "wasd" },
  },
  {
    id: "platformerMovementModifier-1",
    type: "platformerMovementModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: {
      maxSpeed: 220,
      accel: 1800,
      friction: 1600,
      airControl: 0.7,
    },
  },
  {
    id: "gravityModifier-1",
    type: "gravityModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: { gravity: 1400, maxFallSpeed: 900, enabled: true },
  },
  {
    id: "groundModifier-1",
    type: "groundModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: { solidTags: ["solid", "one-way-platform"], emitTag: "player" },
  },
  {
    id: "jumpModifier-1",
    type: "jumpModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: {
      jumpVelocity: 520,
      variableHeightCutoff: 180,
      coyoteMs: 100,
      bufferMs: 120,
      maxJumps: 1,
      emitTag: "player",
    },
  },
  {
    id: "cameraFollowModifier-1",
    type: "cameraFollowModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: {
      followX: true,
      followY: false,
      deadW: 80,
      deadH: 40,
      lerp: 0.15,
      offsetX: 0,
      offsetY: 0,
    },
  },
  {
    id: "graphicGroup-floor",
    type: "graphicGroup",
    position: { x: 320, y: 40 },
    data: {
      label: "Floor",
      groupX: 800,
      groupY: 420,
      collision: true,
      physicsType: "fixed",
      invisible: false,
      tags: ["solid"],
      shapes: [
        {
          id: "floor-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 1600,
          h: 40,
          color: "gray",
        },
      ],
    },
  },
  {
    id: "graphicGroup-platform-a",
    type: "graphicGroup",
    position: { x: 320, y: 320 },
    data: {
      label: "Platform A",
      groupX: 320,
      groupY: 320,
      collision: true,
      physicsType: "fixed",
      invisible: false,
      tags: ["solid"],
      shapes: [
        {
          id: "plat-a-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 180,
          h: 20,
          color: "gray",
        },
      ],
    },
  },
  {
    id: "graphicGroup-platform-b",
    type: "graphicGroup",
    position: { x: 320, y: 600 },
    data: {
      label: "Platform B",
      groupX: 620,
      groupY: 260,
      collision: true,
      physicsType: "fixed",
      invisible: false,
      tags: ["solid"],
      shapes: [
        {
          id: "plat-b-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 160,
          h: 20,
          color: "gray",
        },
      ],
    },
  },
  {
    id: "graphicGroup-platform-c",
    type: "graphicGroup",
    position: { x: 320, y: 880 },
    data: {
      label: "Platform C",
      groupX: 920,
      groupY: 200,
      collision: true,
      physicsType: "fixed",
      invisible: false,
      tags: ["solid"],
      shapes: [
        {
          id: "plat-c-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 220,
          h: 20,
          color: "gray",
        },
      ],
    },
  },
  // --- Scene 2 + a pair of doors that wire scene-1 <-> scene-2 ---
  {
    id: "scene-2",
    type: "scene",
    position: { x: 1160, y: 720 },
    data: {
      label: "Scene 2",
      width: 1200,
      height: 600,
      cellSize: 32,
      showGrid: false,
      // Same blue as scene-1 — red bg hid the red player. If you want them
      // visually distinct, swap to a different color via the Scene node UI.
      backgroundColor: "blue",
      cameraX: 320,
      cameraY: 240,
      cameraZoom: 1,
    },
  },
  {
    id: "graphicGroup-floor-2",
    type: "graphicGroup",
    position: { x: 600, y: 40 },
    data: {
      label: "Floor (Scene 2)",
      groupX: 600,
      groupY: 420,
      collision: true,
      physicsType: "fixed",
      invisible: false,
      tags: ["solid"],
      shapes: [
        {
          id: "floor-2-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 1200,
          h: 40,
          color: "gray",
        },
      ],
    },
  },
  {
    id: "graphicGroup-door-to-2",
    type: "graphicGroup",
    position: { x: 320, y: 1160 },
    data: {
      label: "Door → Scene 2",
      groupX: 1500,
      groupY: 360,
      collision: true,
      physicsType: "passive",
      invisible: false,
      tags: ["door-to-2"],
      shapes: [
        {
          id: "door-to-2-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 30,
          h: 60,
          color: "yellow",
        },
      ],
    },
  },
  {
    id: "graphicGroup-door-to-1",
    type: "graphicGroup",
    position: { x: 600, y: 320 },
    data: {
      label: "Door → Scene 1",
      groupX: 80,
      groupY: 360,
      collision: true,
      physicsType: "passive",
      invisible: false,
      tags: ["door-to-1"],
      shapes: [
        {
          id: "door-to-1-rect",
          kind: "rect",
          x: 0,
          y: 0,
          w: 30,
          h: 60,
          color: "yellow",
        },
      ],
    },
  },
  // Collision rules on the player wiring tag → switchScene action.
  {
    id: "collisionRuleModifier-door-to-2",
    type: "collisionRuleModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: {
      target: "door-to-2",
      action: "switchScene",
      targetSceneId: "scene-2",
      sceneSpawnX: 200,
      sceneSpawnY: 320,
    },
  },
  {
    id: "collisionRuleModifier-door-to-1",
    type: "collisionRuleModifier",
    parentId: "actor-1",
    position: { x: 4, y: 9999 },
    style: { width: 232 },
    data: {
      target: "door-to-1",
      action: "switchScene",
      targetSceneId: "scene-1",
      sceneSpawnX: 200,
      sceneSpawnY: 320,
    },
  },
];

export const platformerEdges = [
  { id: "e-pf-a1-s1", source: "actor-1", target: "scene-1" },
  { id: "e-pf-floor-s1", source: "graphicGroup-floor", target: "scene-1" },
  { id: "e-pf-pa-s1", source: "graphicGroup-platform-a", target: "scene-1" },
  { id: "e-pf-pb-s1", source: "graphicGroup-platform-b", target: "scene-1" },
  { id: "e-pf-pc-s1", source: "graphicGroup-platform-c", target: "scene-1" },
  { id: "e-pf-door-to-2-s1", source: "graphicGroup-door-to-2", target: "scene-1" },
  { id: "e-pf-s1-g1", source: "scene-1", target: "game-1" },
  { id: "e-pf-floor-s2", source: "graphicGroup-floor-2", target: "scene-2" },
  { id: "e-pf-door-to-1-s2", source: "graphicGroup-door-to-1", target: "scene-2" },
  { id: "e-pf-s2-g1", source: "scene-2", target: "game-1" },
];
