// AUTO-GENERATED by scripts/gen-td.mjs — pixel waypoints matching the drawn
// dirt paths in public/maps/td-1.tmj / td-2.tmj. Edit the polylines in the
// script and re-run, don't hand-edit.
export type Waypoint = { x: number; y: number };
export const TD_PATH_1: Waypoint[] = [{"x":8,"y":152},{"x":104,"y":152},{"x":104,"y":56},{"x":232,"y":56},{"x":232,"y":216},{"x":360,"y":216},{"x":360,"y":136},{"x":424,"y":136}];
export const TD_PATH_2: Waypoint[] = [{"x":8,"y":56},{"x":168,"y":56},{"x":168,"y":216},{"x":296,"y":216},{"x":296,"y":104},{"x":424,"y":104}];
