// Throwaway author tool for the Tower Defense maps. Run once:
//   node scripts/gen-td.mjs
// Writes public/maps/td-1.tmj, td-2.tmj (floor + dirt path + nature decor) and
// src/templates/tdPaths.ts (the pixel waypoints, kept in sync with the drawn
// path). Tiles: TilesetFloor base=local 224 (grass), path=local 177 (dirt);
// TilesetNature tuft=local 194.

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MAPS = join(__dirname, "..", "public", "maps");
const TPL = join(__dirname, "..", "src", "templates");

const W = 30;
const H = 20;
const TILE = 16;

const FLOOR_FIRST = 1;
const FLOOR_COLS = 22;
const FLOOR_TILES = 572; // 22 x 26
const NATURE_FIRST = FLOOR_FIRST + FLOOR_TILES; // 573
const NATURE_COLS = 24;
const NATURE_TILES = 504; // 24 x 21

const BASE_GID = FLOOR_FIRST + 154; // grass (green-dominant)
const PATH_GID = FLOOR_FIRST + 177; // dirt
const TUFT_GID = NATURE_FIRST + 194; // green tuft

// Axis-aligned waypoint polylines (grid cells). Last cell = the base.
// Kept within the top ~14 rows so the path/base never sit under the bottom
// toolbar, which docks over the lower ~4 rows of the canvas.
const LEVEL1 = [[0, 9], [6, 9], [6, 3], [14, 3], [14, 13], [22, 13], [22, 8], [26, 8]];
const LEVEL2 = [[0, 3], [10, 3], [10, 13], [18, 13], [18, 6], [26, 6]];
const NATURE1 = [[3, 2], [12, 11], [25, 4], [4, 12], [27, 11], [18, 1], [9, 7]];
const NATURE2 = [[3, 11], [14, 4], [24, 12], [6, 11], [28, 2], [20, 9], [12, 8]];

const tilesets = () => [
  {
    firstgid: FLOOR_FIRST,
    name: "floor",
    image: "../adventure/Backgrounds/Tilesets/TilesetFloor.png",
    imagewidth: 352,
    imageheight: 417,
    columns: FLOOR_COLS,
    tilecount: FLOOR_TILES,
    tilewidth: TILE,
    tileheight: TILE,
    margin: 0,
    spacing: 0,
  },
  {
    firstgid: NATURE_FIRST,
    name: "nature",
    image: "../adventure/Backgrounds/Tilesets/TilesetNature.png",
    imagewidth: 384,
    imageheight: 336,
    columns: NATURE_COLS,
    tilecount: NATURE_TILES,
    tilewidth: TILE,
    tileheight: TILE,
    margin: 0,
    spacing: 0,
  },
];

function ground(cells) {
  const d = new Array(W * H).fill(BASE_GID);
  const put = (c, r) => {
    if (c >= 0 && c < W && r >= 0 && r < H) d[r * W + c] = PATH_GID;
  };
  for (let i = 0; i < cells.length - 1; i++) {
    let [c0, r0] = cells[i];
    const [c1, r1] = cells[i + 1];
    const dc = Math.sign(c1 - c0);
    const dr = Math.sign(r1 - r0);
    put(c0, r0);
    while (c0 !== c1 || r0 !== r1) {
      if (c0 !== c1) c0 += dc;
      else if (r0 !== r1) r0 += dr;
      put(c0, r0);
    }
  }
  return d;
}

function natureLayer(spots) {
  const d = new Array(W * H).fill(0);
  for (const [c, r] of spots) {
    if (c >= 0 && c < W && r >= 0 && r < H) d[r * W + c] = TUFT_GID;
  }
  return d;
}

function buildMap(cells, natureSpots) {
  return {
    compressionlevel: -1,
    width: W,
    height: H,
    infinite: false,
    orientation: "orthogonal",
    renderorder: "right-down",
    tiledversion: "1.12.1",
    version: "1.10",
    type: "map",
    tilewidth: TILE,
    tileheight: TILE,
    nextlayerid: 4,
    nextobjectid: 1,
    tilesets: tilesets(),
    layers: [
      { id: 1, name: "ground", type: "tilelayer", width: W, height: H, x: 0, y: 0, opacity: 1, visible: true, data: ground(cells) },
      { id: 2, name: "nature", type: "tilelayer", width: W, height: H, x: 0, y: 0, opacity: 1, visible: true, data: natureLayer(natureSpots) },
    ],
  };
}

const toWaypoints = (cells) => cells.map(([c, r]) => ({ x: c * TILE + TILE / 2, y: r * TILE + TILE / 2 }));

mkdirSync(MAPS, { recursive: true });
writeFileSync(join(MAPS, "td-1.tmj"), JSON.stringify(buildMap(LEVEL1, NATURE1), null, 1));
writeFileSync(join(MAPS, "td-2.tmj"), JSON.stringify(buildMap(LEVEL2, NATURE2), null, 1));

const pathsTs =
  "// AUTO-GENERATED by scripts/gen-td.mjs — pixel waypoints matching the drawn\n" +
  "// dirt paths in public/maps/td-1.tmj / td-2.tmj. Edit the polylines in the\n" +
  "// script and re-run, don't hand-edit.\n" +
  "export type Waypoint = { x: number; y: number };\n" +
  `export const TD_PATH_1: Waypoint[] = ${JSON.stringify(toWaypoints(LEVEL1))};\n` +
  `export const TD_PATH_2: Waypoint[] = ${JSON.stringify(toWaypoints(LEVEL2))};\n`;
writeFileSync(join(TPL, "tdPaths.ts"), pathsTs);

console.log("wrote td-1.tmj, td-2.tmj and src/templates/tdPaths.ts");
console.log("L1 waypoints:", JSON.stringify(toWaypoints(LEVEL1)));
console.log("L2 waypoints:", JSON.stringify(toWaypoints(LEVEL2)));
